{{- if .Values.ingress.enabled -}}
# Traefik IngressRoute
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "tinyauth.name" . }}
  labels:
    {{- include "tinyauth.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  entryPoints:
    {{- range .Values.ingress.entryPoints | default (list "websecure") }}
    - {{ . }}
    {{- end }}
  routes:
    - kind: Rule
      match: Host(`auth.allapps.me`)
      services:
        - kind: Service
          name: {{ include "tinyauth.name" . }}
          port: {{ .Values.service.port }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- toYaml .Values.ingress.tls | nindent 4 }}
  {{- end }}
{{- end }}
