apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: certificate-allapps
  namespace: cert-manager
spec:
  secretName: certificate-allapps-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
    - "*.allapps.me"
    - "allapps.me"
