apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    # Serveur Letâ€™s Encrypt (production)
    # server: https://acme-v02.api.letsencrypt.org/directory
    # TEST
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: benjaminherve.pro@gmail.com
    privateKeySecretRef:
      name: letsencrypt-key
    solvers:
      - selector:
          dnsZones:
            - allapps.me
        dns01:
          webhook:
            groupName: acme.allapps.me
            solverName: porkbun
            config:
              apiKeySecretRef:
                name: porkbun-key
                key: api-key
              secretKeySecretRef:
                name: porkbun-key
                key: secret-key