apiVersion: v1
kind: ServiceAccount
metadata:
  name: porkbun-webhook
  namespace: cert-manager
  

---
  
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: porkbun-webhook
  namespace: cert-manager
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch"]



---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: porkbun-webhook
  namespace: cert-manager
subjects:
  - kind: ServiceAccount
    name: porkbun-webhook
    namespace: cert-manager
roleRef:
  kind: Role
  name: porkbun-webhook
  apiGroup: rbac.authorization.k8s.io