apiVersion: traefik.io/v1alpha1
kind: TLSStore
metadata:
  name: allapps-tlsstore
  namespace: cert-manager   # le namespace o√π est le secret
spec:
  defaultCertificate:
    secretName: certificate-allapps-tls
