apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: ddnsupdater
  namespace: ddnsupdater
  annotations:
    kubernetes.io/ingress.class: traefik
    gethomepage.dev/href: "https://dns.allapps.me/"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/group: Network
    gethomepage.dev/icon: ddns-updater.png
    gethomepage.dev/name: "DDNS Updater"
    gethomepage.dev/pod-selector: ""
    gethomepage.dev/weight: "10" # optional
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`ddns.allapps.me`)
      services:
      - kind: Service
        name: ddnsupdater
        port: 80
  tls:
      certResolver: letsencrypt
