apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tinyauth
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
spec:
  project: default
  source:
    repoURL: git@github.com:BenLikeCode/argocd.git
    path: charts/tinyauth
    targetRevision: main
  destination:
    server: "https://kubernetes.default.svc"
    namespace: tinyauth
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true