apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "home-assistant.fullname" . }}-pv
  labels:
    {{- include "home-assistant.labels" . | nindent 4 }}
spec:
  capacity:
    storage: 512Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /home-assistant-pv #set you own location
  claimRef:
    name: {{ include "home-assistant.fullname" . }}-pv


---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "home-assistant.fullname" . }}-time-pvc
  labels:
    {{- include "home-assistant.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 1Mi
  hostPath:
    path: /etc/localtime
  claimRef:
    name: {{ include "home-assistant.fullname" . }}-time-pvc
    namespace: default