{{- if .Values.ingress.enabled -}}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "stirlingpdf.name" . }}
  labels:
    {{- include "stirlingpdf.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  entryPoints:
    - {{ .Values.ingress.entryPoints | default "websecure" }}
  routes:
    - kind: Rule
      match: Host(`pdf.allapps.me`)
      services:
        - kind: Service
          name: {{ include "stirlingpdf.name" . }}
          port: {{ .Values.service.port }}
      middlewares:
        - name: tinyauth-tinyauth@kubernetescrd
  tls:
      certResolver: letsencrypt
{{- end }}
